name: kal_mysql_client
description: Server library to interact with the mysql database.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  models:
    git:
      url: 'https://github.com/SuperMuel/Kal'
      path: shared/models
  validated_objects:  
    git:
      url: 'https://github.com/SuperMuel/Kal'
      path: shared/validated_objects

  mysql_client: ^0.0.27
