name: server
description: Official server for the Kal service
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0
  dartz: ^0.10.1

  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  models:
    git:
      url: https://github.com/SuperMuel/Kal
      path: 'shared/models'
  shared:
    git: 
      url: https://github.com/SuperMuel/Kal
      path: shared/shared

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
