name: server
description: Official server for the Kal service
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  freezed_annotation: ^2.2.0

  kal_mysql_client:
    path: packages/kal_mysql_client
  mysql_client: ^0.0.27

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
