-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;

SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KAL` DEFAULT CHARACTER SET UTF8;

USE `KAL`;

-- -----------------------------------------------------
-- Table `kal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`USERS` (
  `USERNAME` VARCHAR(20) NOT NULL,
  `UID` VARCHAR(128) NOT NULL COMMENT 'If more than 128 characters, that\'S WEIRD BUT ALWAYS THROW A SERVER EXCEPTION AND ISSUE A WARNING',
  `access_token` VARCHAR(4096) NULL,
  `refresh_token` VARCHAR(4096) NULL,
  `creation_dt` DATETIME NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `firebase_auth_id_UNIQUE` (`uid` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `kal`.`mirrors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`MIRRORS` (
  `ID` VARCHAR(36) NOT NULL,
  `TITLE` VARCHAR(50) NOT NULL,
  `DESCRIPTION` TEXT(1000) NULL,
  `OWNER` VARCHAR(20) NULL,
  `PUBLIC` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `CREATION_DT` DATETIME NOT NULL,
  `LAST_MODIFICATION_DT` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `OWNER_IDX` (`OWNER` ASC) VISIBLE,
  CONSTRAINT `MIRRORS_OWNER` FOREIGN KEY (`OWNER`) REFERENCES `KAL`.`USERS` (`USERNAME`) ON DELETE SET NULL ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `kal`.`mirrors_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`MIRRORS_LIKES` (
  `USER` VARCHAR(20) NOT NULL,
  `MIRROR` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USER`, `MIRROR`),
  INDEX `MIRROR_IDX` (`MIRROR` ASC) VISIBLE,
  CONSTRAINT `MIRRORS_LIKES_USER` FOREIGN KEY (`USER`) REFERENCES `KAL`.`USERS` (`USERNAME`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `MIRRORS_LIKES_MIRROR` FOREIGN KEY (`MIRROR`) REFERENCES `KAL`.`MIRRORS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `kal`.`mirror_subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`MIRROR_SUBSCRIPTIONS` (
  `ID` VARCHAR(36) NOT NULL,
  `USER` VARCHAR(20) NOT NULL,
  `MIRROR` VARCHAR(36) NOT NULL,
  `ENABLED` TINYINT(1) NOT NULL,
  `LAST_REFRESH_DT` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `USER_IDX` (`USER` ASC) VISIBLE,
  INDEX `MIRROR_IDX` (`MIRROR` ASC) VISIBLE,
  CONSTRAINT `MIRROR_SUBSCRIPTION_USER` FOREIGN KEY (`USER`) REFERENCES `KAL`.`USERS` (`USERNAME`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `MIRROR_SUBSCRIPTION_MIRROR` FOREIGN KEY (`MIRROR`) REFERENCES `KAL`.`MIRRORS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `kal`.`mirror_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`MIRROR_RULES` (
  `ID` VARCHAR(36) NOT NULL,
  `MIRROR` VARCHAR(36) NOT NULL,
  `RULE_JSON` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `MIRROR_RULES_MIRROR` FOREIGN KEY (`MIRROR`) REFERENCES `KAL`.`MIRRORS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `kal`.`schedule_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`SCHEDULE_PROVIDER` (
  `ID` VARCHAR(36) NOT NULL,
  `TITLE` VARCHAR(128) NOT NULL,
  `PARENT_SCHEDULE_PROVIDER` VARCHAR(36) NULL,
  PRIMARY KEY (`ID`),
  INDEX `SCHEDULE_PROVIDER_PARENT_IDX` (`PARENT_SCHEDULE_PROVIDER` ASC) VISIBLE,
  CONSTRAINT `SCHEDULE_PROVIDER_PARENT` FOREIGN KEY (`PARENT_SCHEDULE_PROVIDER`) REFERENCES `KAL`.`SCHEDULE_PROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `kal`.`source_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`SOURCE_SCHEDULE` (
  `ID` VARCHAR(36) NOT NULL,
  `TITLE` VARCHAR(128) NOT NULL,
  `ICSURL` VARCHAR(2048) NULL,
  `PARENT_SCHEDULE_PROVIDER` VARCHAR(36) NOT NULL,
  `CREATION_DT` DATETIME NULL,
  PRIMARY KEY (`ID`),
  INDEX `SOURCE_SCHEDULE_PARENT_IDX` (`PARENT_SCHEDULE_PROVIDER` ASC) VISIBLE,
  CONSTRAINT `SOURCE_SCHEDULE_PARENT` FOREIGN KEY (`PARENT_SCHEDULE_PROVIDER`) REFERENCES `KAL`.`SCHEDULE_PROVIDER` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE = INNODB;

-- -----------------------------------------------------
-- Table `kal`.`mirror_source_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KAL`.`MIRROR_SOURCE_SCHEDULES` (
  `MIRROR` VARCHAR(36) NOT NULL,
  `SOURCE_SCHEDULE` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`MIRROR`, `SOURCE_SCHEDULE`),
  INDEX `MIRROR_SOURCE_SCHEDULES_MIRROR_SOURCE_SCHEDULE_IDX` (`SOURCE_SCHEDULE` ASC) VISIBLE,
  CONSTRAINT `MIRROR_SOURCE_SCHEDULES_MIRROR` FOREIGN KEY (`MIRROR`) REFERENCES `KAL`.`MIRRORS` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT `MIRROR_SOURCE_SCHEDULES_MIRROR_SOURCE_SCHEDULE` FOREIGN KEY (`SOURCE_SCHEDULE`) REFERENCES `KAL`.`SOURCE_SCHEDULE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB;

SET SQL_MODE=@OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;