name: models
description: Base models used by the Kal api
version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'


dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.0
  json_serializable: ^6.5.3
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  freezed_annotation: ^2.2.0
