name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:

dev_dependencies:
  build_runner: ^2.2.1
  dartz_test: ^0.1.0
  freezed: ^2.1.1
  json_serializable: ^6.5.0
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  meta: ^1.8.0
  uuid: ^3.0.6
