-- MySQL Script generated by MySQL Workbench
-- Sat Oct 22 17:34:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `username` VARCHAR(20) NOT NULL,
  `firebase_auth_uid` VARCHAR(128) NOT NULL COMMENT 'If more than 128 characters, that\'s weird but always throw a server exception and issue a warning',
  `access_token` VARCHAR(4096) NULL,
  `refresh_token` VARCHAR(4096) NULL,
  `creation_dt` DATETIME NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `firebase_auth_id_UNIQUE` (`firebase_auth_uid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mirrors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mirrors` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` TEXT(1000) NULL,
  `owner` VARCHAR(20) NULL,
  `public` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `creation_dt` DATETIME NOT NULL,
  `last_modification_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `owner_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner`)
    REFERENCES `mydb`.`users` (`username`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mirrors_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mirrors_likes` (
  `user` VARCHAR(20) NOT NULL,
  `mirror` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`user`, `mirror`),
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `mirror`
    FOREIGN KEY (`user` , `mirror`)
    REFERENCES `mydb`.`mirrors` (`id` , `id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mirror_subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mirror_subscriptions` (
  `id` VARCHAR(36) NOT NULL,
  `user` VARCHAR(20) NOT NULL,
  `mirror` VARCHAR(36) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `last_refresh_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`user` ASC) VISIBLE,
  INDEX `mirror_idx` (`mirror` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`users` (`username`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `mirror`
    FOREIGN KEY (`mirror`)
    REFERENCES `mydb`.`mirrors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mirror_rules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mirror_rules` (
  `id` VARCHAR(36) NOT NULL,
  `mirror` VARCHAR(36) NOT NULL,
  `rule_json` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `mirror`
    FOREIGN KEY (`mirror`)
    REFERENCES `mydb`.`mirrors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule_provider` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `parent_schedule_provider` VARCHAR(36) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `parent_schedule_provider`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`schedule_provider` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`source_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`source_schedule` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `icsUrl` VARCHAR(2048) NULL,
  `parent_schedule_provider` VARCHAR(36) NOT NULL,
  `creation_dt` DATETIME NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `parent_schedule_provider`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`schedule_provider` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mirror_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mirror_groups` (
  `mirror` VARCHAR(36) NOT NULL,
  `source_schedule` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`mirror`, `source_schedule`),
  CONSTRAINT `mirror`
    FOREIGN KEY (`mirror`)
    REFERENCES `mydb`.`mirrors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `source_schedule`
    FOREIGN KEY (`mirror` , `source_schedule`)
    REFERENCES `mydb`.`source_schedule` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
